export const ADD_TO_MY_POKEMON = 'ADD_TO_MY_POKEMON';
export const DELETE_FROM_MY_POKEMON = 'DELETE_FROM_MY_POKEMON';

export const POKEMONS = {
  GET_POKEMONS_REQUEST: 'GET_POKEMONS_REQUEST',
  GET_POKEMONS_SUCCESS: 'GET_POKEMONS_SUCCESS',
  GET_POKEMONS_FAILED: 'GET_POKEMONS_FAILED',

  GET_POKEMON_DETAIL_REQUEST: 'GET_POKEMONS_DETAIL_REQUEST',
  GET_POKEMONS_DETAIL_SUCCESS: 'GET_POKEMONS_DETAIL_SUCCESS',
  GET_POKEMONS_DETAIL_FAILED: 'GET_POKEMONS_DETAIL_FAILED',
};
